### ISSUE TITLE
Version '7.58.0-2ubuntu3.7' for 'curl' was not found

### ISSUE THREAD

**Issue by JA1lE1** [panovvv/bigdata-docker-compose#1]
Hi, thank you for sharing your docker-compose.
I try to follow your steps and it seems something go wrong when the base dockerfile goes to Step 3/53 
- (Step 3/53 : RUN apt-get update && apt-get install -y --no-install-recommends         ***curl=7.58.0-2ubuntu3.7***        unzip=6.0-21ubuntu1         ssh=1:7.6p1-4ubuntu0.3         openjdk-8-jdk-headless=8u222-b10-1ubuntu1~18.04.1  && rm -rf /var/lib/apt/lists/*)
- The ERROR shows that **E: Version '7.58.0-2ubuntu3.7' for 'curl' was not found**
- I have come across  it when i tried it on ubuntu:18.04 LTS
- i just wonder if it will go wrong when i want to change the " curl=7.58.0-2ubuntu3.7" to  "curl"  on the base dockerfile?

**Comment by panovvv** [comment]
Hey!
Yes, I'd stumbled upon this myself too :)
Looks like they updated the package version to 7.58.0-2ubuntu3.8 (why did I base my images off the latest Ubuntu again? That was the worst decision...)
You can either:
- pull the latest master, I bumped the version two weeks ago but forgot to push it, doing it as we speak,
-  change " curl=7.58.0-2ubuntu3.7" to "curl" - this will just pull the latest package version each time you build your Docker image. I fixed the versions only because it's a good practice: https://github.com/hadolint/hadolint/wiki/DL3008

**Comment by panovvv** [comment]
@JA1lE1 Can you tell if this solved the issue for you? I'll mark it "closed" if it did.

**Comment by JA1lE1** [comment]
@panovvv  yes，your solution help me a lot . 👍  Thank you for your help. I am  sorry  i forgot to reply to you in time.
