### ISSUE TITLE
Zeppelin no longer reads example workbook into application on load

### ISSUE THREAD

**Issue by AbbyJoy** [panovvv/bigdata-docker-compose#5]
I think it might have been a change to the directory structure for Zeppelin 9 that for whatever reason just got picked up on release 2.5.2 of bigdata-docker-compose, but there was a significant change to directory structure that Zeppelin reads from disk. However, you can still use the json file in the repository to import the notebook into the application instead of getting it on load of the application.

Would probably be a good idea to save the new directory structure into the bigdata-docker-compose repo for clarity eventually.

**Comment by AbbyJoy** [comment]
Looks like the introduced the concept of a .zpln file, which looks like just a json file for zeppelin notebooks.

**Comment by panovvv** [comment]
I was wondering if it's just me or the new version of Zeppelin actually doesn't even migrate the old notebook format to the new one automatically... Turns out it's not just me! It was a no-brainer - I just renamed the old .json notebook to .zpln and it all worked.
Meh. I really wish Zeppelin developers would do that.

**Comment by panovvv** [comment]
Fix pushed - feel free to close if it works for you.
